baseURL = "https://cognitivegears.github.io/"
languageCode = "en-us"
title = "Retro Tech Rewind"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "terminal"
preserveTaxonomyNames = true
paginate=5

[params]
    # terminal
    contentTypeName="posts"
    themeColor="orange"
    showMenuItems=3
    showLanguageSelector=false
    fillWidthTheme=false
    centerTheme=false

    showLastUpdated=false

    # Urls for social networks
    mastodon = "https://bitbang.social/@cognitivegears"
    lemmy = "https://lemmy.sdf.org/u/cognitivegears"
    matrix = "https://matrix.to/#/@cognitivegears:matrix.org"
    github = "https://github.com/cognitivegears"

    favicon = "favicon.ico"
[params.copyright]
    name = "Nathan Byrd"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = "[All content distributed under CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[languages]
  [languages.en]
    languageName = "English"
    title = "Retro Tech Rewind"
    subtitle = "Be kind, please rewind."
    owner = "Nathan Byrd"
    keywords = "retro tech vintage apple tandy commodore ibm"
    copyright = "Copyright &copy; 2023 Nathan Byrd. All content distributed under CC BY-SA 4.0"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Retro Tech Rewind"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"

